### PR TITLE
feat: all contributors

### PR DESCRIPTION
**Pull request by suitupstan**
Also install this bot for this to work: https://github.com/apps/allcontributors/installations/new

### CODE REVIEW

**Comment by adityamangal1** [comment]
Hey @krishguptadev Great work. I installed the bot but can you show some snapshots like what exactly the bot does or how?

**Comment by suitupstan** [comment]
Checkout these docs: https://allcontributors.org/docs/en/bot/usage

**Comment by adityamangal1** [comment]
@all-contributors please add @krishguptadev  for documentation features

**Comment by adityamangal1** [comment]
@all-contributors please add @krishguptadev  for documentation features

**Review by adityamangal1 — APPROVED** [review]

**Pull request merged**
